In [19]:
import pandas as pd
import numpy as np

In [20]:
landscape_cat = {
    "ag": [
        "Corn",
        "Cotton",
        "Rice",
        "Sorghum",
        "Soybeans",
        "Sunflower",
        "Peanuts",
        "Tobacco",
        "Sweet Corn",
        "Pop or Orn Corn",
        "Mint",
        "Barley",
        "Durum Wheat",
        "Spring Wheat",
        "Winter Wheat",
        "Other Small Grains",
        "Dbl Crop WinWht/Soybeans",
        "Rye",
        "Oats",
        "Millet",
        "Speltz",
        "Canola",
        "Flaxseed",
        "Safflower",
        "Rape Seed",
        "Mustard",
        "Alfalfa",
        "Other Hay/Non Alflafa",
        "Camelina",
        "Buckwheat",
        "Sugarbeets",
        "Dry Beans",
        "Potatoes",
        "Other Crops",
        "Sugarcane",
        "Sweet Potatoes",
        "Misc Vegs & Fruits",
        "Watermelons",
        "Onions",
        "Cucumbers",
        "Chick Peas",
        "Lentils",
        "Peas",
        "Tomatoes",
        "Caneberries",
        "Hops",
        "Herbs",
        "Clover/Wildflowers",
        "Sod/Grass Seed",
        "Switchgrass",
        "Cherries",
        "Peaches",
        "Apples",
        "Grapes",
        "Christmas Trees",
        "Other Tree Crops",
        "Citrus",
        "Pecans",
        "Almonds",
        "Walnuts",
        "Pears",
        "Pistachios",
        "Triticale",
        "Carrots",
        "Asparagus",
        "Garlic",
        "Cantaloupes",
        "Prunes",
        "Olives",
        "Oranges",
        "Honeydew Melons",
        "Broccoli",
        "Avocados",
        "Peppers",
        "Pomegranates",
        "Nectarines",
        "Greens",
        "Plums",
        "Strawberries",
        "Squash",
        "Apricots",
        "Vetch",
        "Dbl Crop WinWht/Corn",
        "Dbl Crop Oats/Corn",
        "Lettuce",
        "Dbl Crop Triticale/Corn",
        "Pumpkins",
        "Dbl Crop Lettuce/Durum Wht",
        "Dbl Crop Lettuce/Cantaloupe",
        "Dbl Crop Lettuce/Cotton",
        "Dbl Crop Lettuce/Barley",
        "Dbl Crop Durum Wht/Sorghum",
        "Dbl Crop Barley/Sorghum",
        "Dbl Crop WinWht/Sorghum",
        "Dbl Crop Barley/Corn",
        "Dbl Crop WinWht/Cotton",
        "Dbl Crop Soybeans/Cotton",
        "Dbl Crop Soybeans/Oats",
        "Dbl Crop Corn/Soybeans",
        "Blueberries",
        "Cabbage",
        "Cauliflower",
        "Celery",
        "Radishes",
        "Turnips",
        "Eggplants",
        "Gourds",
        "Cranberries",
        "Dbl Crop Barley/Soybeans",
        "Cropland",
    ],
    "nat": [
        "Forest",
        "Shrubland",
        "Barren",
        "Wetlands",
        "Nonag/Undefined",
        "Deciduous Forest",
        "Evergreen Forest",
        "Mixed Forest",
        "Shrubland",
        "Woody Wetlands",
        "Herbaceous Wetlands",
    ],
    "semi_nat": ["Grassland/Pasture",
                 "Grass/Pasture"],
    "dev": [
        "Developed/Open Space",
        "Developed/Low Intensity",
        "Developed/Med Intensity",
        "Developed/High Intensity",
        "Barren",
    ],
    "other": [
        "Aquaculture",
        "Water",
        "Perennial Ice/Snow",
        "Open Water"
    ],
}

In [81]:
metadata = pd.read_csv("../SCM/2023/Landscape/metadata/cdl_metadata_ny_2018.csv")
qgis_df = pd.read_csv(
    "../SCM/2023/Landscape/2018_ny_cdl/2018_ny_cdl_csv/2023_scm_2018_cdl_3000m.csv"
)
qgis_df

,Name,descriptio,timestamp,begin,end,altitudeMo,tessellate,extrude,visibility,drawOrder,...,VALUE_214,VALUE_216,VALUE_219,VALUE_220,VALUE_222,VALUE_225,VALUE_229,VALUE_242,VALUE_243,VALUE_246
0,POV_DUN,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,2,8,0,0
1,DIP_FLE,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,2,0,0,1,0,0
2,DIP_CUR,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,5,2,0,0
3,GAB_STE,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
4,SMI_CRO,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,2,1,0,0
5,SMI_CAN,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,3,0,0
6,SMI_KEL,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
7,SMI_COB,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,3,0,0
8,SMI_DOU,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
9,SMI_MCC,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
10,SMI_HOL,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,3,0,0,0
11,DIP_PAT,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,2,0,0
12,MIL_YOD,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
13,MIL_CHA,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
14,MIL_MCC,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,1,0,0
15,KAT_SAU,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
16,KAT_SAU_2,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
17,KAT_TEE,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,3,0,0
18,KAT_TEE_2,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,3,0,0
19,KAT_HAB_2,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,3,0,0,2,0,0
20,KAT_HAB,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,2,0,0,0,0,0,0,5,0,0
21,KAT_BAR,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
22,SMI_LAT,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,3,0,2,0,0,0
23,SMI_DUR,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
24,SMI_HOF,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
25,SMI_JOH,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,1,0,0,0
26,SMI_JOH_2,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
27,GAB_ALL,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,24,4,0,0
28,KAT_JEF,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
29,KAT_JEF_2,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
30,STA_WIL,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,2,26,0
31,STA_HEM_2,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,24,0,0,0,622,0
32,STA_HEM,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,1113,0
33,STA_SWE,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,2,0,7,0,0,0,23,0
34,STA_COL,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,2,8,0,0,99,0,0,0,373,0
35,WIS_COO_2,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,155,0,0,0,0
36,WIS_COO,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,41,0,0,0,0
37,LET_NOB,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,5,0
38,LET_TAB,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,2,0
39,WIS_HIG,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,2,0,0,0,0,0,0
40,WIS_MEG,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
41,WIS_KEN,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,9,0,0,0,0,0,0
42,ZUE_REE,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,2,0,0,0,299,1
43,DEG_PER_STRIP,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,2,3,0,0
44,DEG_FOU_WOOD,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,2,0,0
45,DEG_DIE_HILL,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,3,0,0,0
46,DEG_DIE_SWC,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,1,3,0,0
47,DEG_YOU_BOCES,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,1,4,0,0
48,DEG_YOU_OSHEA,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,5,0,0
49,DEG_YOU_JONES,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,17,0,0,0
50,DEG_VIL,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,17,0,0,0
51,SEA_HOO,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,2,0,0,0,31,88
52,MIL_HUM,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
53,ONE_TER,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
54,ONE_ADO,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
55,ONE_STA,NaN,NaN,NaN,NaN,NaN,-1,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0

In [82]:
def cdl_processing(cdl_metadata, qgis_csv):
    cdl_metadata["cdl_number"] = "VALUE_" + metadata["cdl_number"].astype("str")
    qgis_csv.rename(
        columns=cdl_metadata.set_index("cdl_number")["cdl_classification"], inplace=True
    )
    qgis_csv = qgis_csv.drop(
        [
            "descriptio",
            "timestamp",
            "begin",
            "end",
            "altitudeMo",
            "tessellate",
            "extrude",
            "visibility",
            "drawOrder",
            "icon",
        ],
        axis=1,
    )
    qgis_csv["Total"] = qgis_csv.sum(axis=1, numeric_only=True)
    qgis_csv['Ag'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['ag'])].sum(axis=1)
    qgis_csv['Nat'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['nat'])].sum(axis=1)
    qgis_csv['Semi_Nat'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['semi_nat'])].sum(axis=1)
    qgis_csv['Dev'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['dev'])].sum(axis=1)
    qgis_csv['Other'] = qgis_csv[qgis_csv.columns.intersection(landscape_cat['other'])].sum(axis=1)
    return qgis_csv

In [83]:
cdl_df = cdl_processing(metadata, qgis_df)
cdl_df

,Name,Corn,Sorghum,Soybeans,Sunflower,Barley,Spring Wheat,Winter Wheat,Rye,Oats,...,Pumpkins,Blueberries,Cabbage,Radishes,Total,Ag,Nat,Semi_Nat,Dev,Other
0,POV_DUN,244,0,34,0,9,0,23,70,40,...,2,8,0,0,57216,2040,39876,6492,3241,120
1,DIP_FLE,12985,7,1255,0,5,0,356,20,170,...,0,1,0,0,57606,23875,23420,3681,2286,6
2,DIP_CUR,5746,62,271,0,4,0,30,8,28,...,5,2,0,0,57302,10815,33974,4387,2011,28
3,GAB_STE,8246,5,240,0,1,0,26,49,19,...,0,0,0,0,58500,13971,25390,8580,7445,621
4,SMI_CRO,5604,0,1862,0,56,96,1,5,143,...,2,1,0,0,58067,8808,11092,6578,2375,39
5,SMI_CAN,5405,2,1120,2,0,0,2,5,662,...,0,3,0,0,58119,14066,21722,7950,3011,499
6,SMI_KEL,15123,4,2390,0,0,4,3,136,127,...,0,0,0,0,58282,18785,15144,3579,4537,2014
7,SMI_COB,3101,3,86,0,1,0,0,18,9,...,0,3,0,0,57723,4977,27072,3596,10113,132
8,SMI_DOU,4422,0,1085,0,20,0,8,2,88,...,0,0,0,0,58459,8629,19565,3922,11352,1014
9,SMI_MCC,6681,8,1532,0,1,0,18,35,59,...,0,0,0,0,58572,11171,21133,7124,2181,65
10,SMI_HOL,8641,0,1270,0,11,0,0,3,2,...,3,0,0,0,58174,11816,21404,2340,2734,1362
11,DIP_PAT,17393,4,5041,0,0,0,3668,12,62,...,0,2,0,0,58175,39164,10642,4271,1851,48
12,MIL_YOD,9664,0,2925,0,183,2,134,0,349,...,0,0,0,0,58352,25860,20054,7604,1532,26
13,MIL_CHA,14418,0,2363,0,7,0,784,0,74,...,0,0,0,0,58415,27358,22402,6022,1081,87
14,MIL_MCC,8963,1,2629,0,3,0,30,58,233,...,0,1,0,0,58211,18272,25873,6693,4355,188
15,KAT_SAU,3691,0,86,1,0,0,251,10,190,...,0,0,0,0,56623,5462,30933,7196,2619,7
16,KAT_SAU_2,4654,0,101,1,0,0,326,16,220,...,0,0,0,0,56628,6736,27244,7827,2176,7
17,KAT_TEE,3328,33,148,0,0,0,22,2,12,...,0,3,0,0,57125,5734,41449,2636,1422,54
18,KAT_TEE_2,4006,1,185,0,0,0,28,3,22,...,0,3,0,0,57141,6686,41037,1996,1480,72
19,KAT_HAB_2,7567,0,1461,0,0,0,92,19,64,...,0,2,0,0,57524,10825,28587,3405,1784,437
20,KAT_HAB,8947,0,3065,0,2,0,77,56,1,...,0,5,0,0,57447,15142,24118,3465,6563,57
21,KAT_BAR,2729,0,311,0,0,0,258,0,1,...,0,0,0,0,56609,4829,41603,3250,2584,699
22,SMI_LAT,10466,0,748,0,14,0,13,2,87,...,2,0,0,0,57778,19840,19627,7960,4625,346
23,SMI_DUR,5348,0,760,0,12,0,23,6,94,...,0,0,0,0,58476,8688,36972,4328,4411,1347
24,SMI_HOF,4523,0,777,0,0,0,10,3,96,...,0,0,0,0,57155,6699,38074,5393,2952,866
25,SMI_JOH,8909,0,1457,0,150,0,102,0,152,...,1,0,0,0,58368,18023,22221,9071,2633,36
26,SMI_JOH_2,3148,0,751,0,5,0,50,4,96,...,0,0,0,0,58482,10705,27594,7474,9448,354
27,GAB_ALL,3218,0,18,0,0,0,2,4,9,...,24,4,0,0,58217,4600,30477,2121,14447,4488
28,KAT_JEF,3458,0,595,0,0,0,65,0,56,...,0,0,0,0,56958,5156,30849,5377,2648,61
29,KAT_JEF_2,3221,0,33,0,0,0,17,0,54,...,0,0,0,0,57012,3599,35949,3160,1881,63
30,STA_WIL,12365,0,2217,4,3,0,4285,32,75,...,0,2,26,0,58382,30114,15798,7700,3687,108
31,STA_HEM_2,15680,8,3484,1,4,0,4360,490,35,...,0,0,622,0,58100,32606,13532,6081,4337,284
32,STA_HEM,15292,28,5881,5,3,0,747,16,45,...,0,0,1113,0,58198,33925,13326,6173,2483,1249
33,STA_SWE,8329,5,2237,0,0,0,1682,8,10,...,0,0,23,0,57977,25549,24145,5191,2058,77
34,STA_COL,7195,0,2816,0,1,0,2582,9,9,...,0,0,373,0,58702,18641,20954,11461,6104,480
35,WIS_COO_2,2822,3,1567,5,0,2,30,1,9,...,0,0,0,0,56249,7959,33804,7883,2972,159
36,WIS_COO,4728,0,2670,17,0,0,143,10,17,...,0,0,0,0,56308,13947,23746,10548,1802,355
37,LET_NOB,22983,0,5041,0,0,0,544,0,2,...,0,0,5,0,58093,42686,10053,2730,2040,29
38,LET_TAB,14977,0,239,0,0,0,954,5,46,...,0,0,2,0,57685,30599,22072,2090,2356,299
39,WIS_HIG,57,0,12,0,0,0,0,13,0,...,0,0,0,0,56079,917,38029,1325,7685,6982
40,WIS_MEG,1392,1204,784,13,548,0,174,36,42,...,0,0,0,0,56531,5697,26551,7550,11535,308
41,WIS_KEN,482,0,78,2,0,0,3,3,0,...,0,0,0,0,55935,9228,17483,3343,15589,8956
42,ZUE_REE,7289,1,5912,2,0,0,2611,33,285,...,0,0,299,1,57948,22447,7628,3011,2867,21248
43,DEG_PER_STRIP,7777,11,1146,0,14,0,53,17,127,...,2,3,0,0,57744,15503,29176,4827,2259,50
44,DEG_FOU_WOOD,11683,2,148,0,9,0,126,18,35,...,0,2,0,0,57571,20534,19607,6898,2916,46
45,DEG_DIE_HILL,5020,4,617,0,0,0,26,9,70,...,3,0,0,0,57617,8253,23030,5617,15814,1166
46,DEG_DIE_SWC,6677,5,240,0,0,0,8,8,31,...,1,3,0,0,57676,10954,31307,5615,2580,43
47,DEG_YOU_BOCES,6261,2,564,0,0,0,13,4,41,...,1,4,0,0,57644,10155,17776,5453,20724,122
48,DEG_YOU_OSHEA,8288,2,162,0,0,2,6,4,39,...,0,5,0,0,57695,13962,19621,6027,12101,1152
49,DEG_YOU_JONES,6708,0,295,2,4,0,196,21,217,...,17,0,0,0,57759,14084,28347,3943,4935,2263
50,DEG_VIL,6244,0,459,2,4,7,193,24,231,...,17,0,0,0,57779,13936,29183,4060,4774,2196
51,SEA_HOO,14463,0,8187,4,0,0,4409,169,809,...,0,0,31,88,57656,39493,8366,5145,2293,50
52,MIL_HUM,5431,0,3447,0,238,0,2177,1,13,...,0,0,0,0,58448,14886,25954,6237,9014,7
53,ONE_TER,7027,168,81,0,0,0,0,1,73,...,0,0,0,0,61546,10090,21403,5998,13978,1807
54,ONE_ADO,1949,2,57,0,3,0,7,0,23,...,0,0,0,0,61643,5723,45995,2063,4262,1378
55,ONE_STA,13381,6,17,0,10,0,0,15,27,...,0,0,0,0,61933,17188,35095,1936,2176,67

In [84]:
cdl_df.to_csv('../SCM/2023/Landscape/2018_ny_cdl/2018_ny_cdl_csv/2023_scm_2018_cdl_3000m.csv')